version: 1.0.{build}-{branch}
branches:
  only:
    - master

shallow_clone: false
skip_tags: true
clone_depth: 1

image: Visual Studio 2019

platform:
  - x64

configuration:
  - Debug
  - Release

matrix:
  fast_finish: false

build_script:
  - cmd: git submodule update --init --recursive
  - cmd: cmake -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=%CONFIGURATION% -Bbuild -H.
  - cmd: cd build
  - cmd: msbuild game_launcher.sln
